### ISSUE TITLE
style: common components

### ISSUE THREAD

**Issue by laurenCho9** [Prefitt-11-supreme/11-supreme#1]
### 📃Description
> 공통 컴포넌트 작업

### 📌Todo
- [x] 색상 테마 설정
- [x] 버튼 컴포넌트
- [x] 챗봇 검색 컴포넌트
- [x] 추천 질문 카드 컴포넌트
- [x] 인풋 컴포넌트
- [x] 셀렉트박스 컴포넌트
- [x] 키워드 카드 컴포넌트
- [x] 모달 컴포넌트
- [x] 사이즈 추천 카드 컴포넌트
- [x] 상품 추천 카드 컴포넌트
- [x] 헤더 바 컴포넌트

### 📝ETC
> 기타사항
