### ISSUE TITLE
style: Mypage Modify

### ISSUE THREAD

**Issue by laurenCho9** [Prefitt-11-supreme/11-supreme#23]
### 📃Description
> 마이페이지 ui 수정 및 추가

### 📌Todo
- [x] assets.css.ts => assets.ts 파일명 변경
- [x] 마이페이지 ui
- [x] 사이드메뉴 ui
- [x] 좋아요(상품/브랜드)페이지 ui
- [x] 최근 본 페이지 ui

### 📝ETC
> 기타사항
