### ISSUE TITLE
style: Common Components Modify

### ISSUE THREAD

**Issue by laurenCho9** [Prefitt-11-supreme/11-supreme#46]
### 📃Description
> 공통컴포넌트 수정

### 📌Todo
- [x] header컴포넌트에 text props 추가
- [ ] header컴포넌트에 뒤로가기 기능 추가
- [ ] header컴포넌트에 사이드메뉴 햄버거버튼의 클릭이벤트 추가

### 📝ETC
> 기타사항
