### ISSUE TITLE
Feat: firebase, onboarding ui

### ISSUE THREAD

**Issue by IMIMIMIMIMIMIMIM** [Prefitt-11-supreme/11-supreme#67]
### 📃Description
> 신발등록 데이터 저장, 신발장 데이터 호출, 신발 정보 데이터 호출 & 삭제 & 수정, 온보딩 ui 변경, 유효성검사

### 📌Todo
- [x] 신발등록 데이터 저장
- [x] 신발장 데이터 호출, 신발 정보 데이터 호출 & 삭제 & 수정
- [x] 온보딩 ui 변경
- [x] 신발장 셀렉트박스
- [x] 신발 등록 유효성 검사

### 📝ETC
> 수정 공유 아직 진행 불가
