### ISSUE TITLE
refactor: Login, SignUp Detail

### ISSUE THREAD

**Issue by ayeooong** [Prefitt-11-supreme/11-supreme#80]
### 📃Description
> 로그인/회원가입 관련 세부사항 수정...

### 📌Todo
- [x] 회원가입 첫 번째 페이지에서 두 번째 페이지 넘어갈 때 시간 단축
- [x] 구글 회원가입 시 성별, 생년월일 정보 추가 입력 방식...
- [x] 이메일 찾기, 비밀번호 찾기

### 📝ETC
> x
