### ISSUE TITLE
refactor: Standardize containers, Responsive, Organize assets

### ISSUE THREAD

**Issue by laurenCho9** [Prefitt-11-supreme/11-supreme#87]
### 📃Description
> 컨테이너 표준화, 반응형 디자인 구현, assets.ts 폴더 정리

### 📌Todo
- [ ] 공통 컨테이너 style 적용
- [ ] 브라우저 및 모바일 반응형 작업
- [ ] assets.ts 폴더 정리

### 📝ETC
> 기타사항
